# Generated by Django 5.2 on 2025-06-15 22:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveQuizSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('initial_difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('total_questions', models.IntegerField()),
                ('asked_count', models.IntegerField(default=0)),
                ('last_difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongQuizAnswer',
            fields=[
                ('question', models.TextField(help_text='UThe quiz question')),
                ('submitted', models.CharField(help_text="What the student submitted (e.g. 'B' or 'True').")),
                ('correct', models.CharField(help_text='What the correct answer was.')),
                ('distractors_with_rationale', models.JSONField(blank=True, help_text='[{distractor: str, rationale: str}, …]', null=True)),
                ('reflection_prompt', models.TextField(blank=True, help_text='GPT-generated two-sentence reflection prompt', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Wrong Quiz Answer',
                'verbose_name_plural': 'Wrong Quiz Answers',
                'ordering': ['course'],
            },
        ),
    ]
