# Generated by Django 5.2 on 2025-06-15 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('courses', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptivequizsession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='adaptivequizsession',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.personaldata'),
        ),
        migrations.AddField(
            model_name='wrongquizanswer',
            name='course',
            field=models.ForeignKey(help_text='The course this quiz belongs to.', on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
        migrations.AddField(
            model_name='wrongquizanswer',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_quiz_answers', to='profiles.personaldata'),
        ),
        migrations.AddField(
            model_name='wrongquizanswer',
            name='session',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to='ai_assistant.adaptivequizsession'),
        ),
    ]
