# Generated by Django 5.2 on 2025-06-15 22:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, default='courses/images/default_course_img_E4H4Mp2.jpg', upload_to='courses/images/')),
                ('script', models.TextField(blank=True, help_text='Auto-generated lecture script when a presentation is added.', null=True)),
                ('audio', models.FileField(blank=True, help_text='Auto-generated audio lecture (MP3).', null=True, upload_to='course/audio/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('key_concepts', models.JSONField(blank=True, default=list, help_text="List of key concepts (e.g. ['Loops','Recursion']) that the exam should cover.")),
                ('num_questions', models.PositiveIntegerField(default=10, help_text='Number of MCQ questions to generate per student.')),
                ('duration', models.FloatField(blank=True, help_text='Time in minutes allocated for the exam.', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenEndedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responses', models.JSONField(default=list, help_text='A list of {question: <string>, answer: <string>} objects.')),
            ],
            options={
                'verbose_name': 'Open-Ended Response',
                'verbose_name_plural': 'Open-Ended Responses',
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='presentations/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('questions', models.JSONField(blank=True, default=list, help_text='Generated exam questions, each as { question: str, choices: [str, str, str, str], correct_index: int }')),
                ('answers', models.JSONField(blank=True, default=dict, help_text="What the student submitted, e.g. { '0': 2, '1': 0, ... }")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('SUBMITTED', 'Submitted')], default='PENDING', max_length=10)),
                ('retries', models.IntegerField(default=0)),
                ('grade', models.FloatField(blank=True, help_text='Final grade after auto-grading or teacher review', null=True)),
                ('personal_feedback', models.TextField(blank=True, help_text="Teacher's feedback after reviewing the student exam.", null=True)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at_client', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(max_length=2000)),
                ('script', models.CharField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WrongExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(help_text="Unique key/slug for the exam question (e.g. 'exam_q17')", max_length=100)),
                ('submitted', models.CharField(help_text='What the student submitted.', max_length=255)),
            ],
            options={
                'verbose_name': 'Wrong Exam Answer',
                'verbose_name_plural': 'Wrong Exam Answers',
                'ordering': ['exam'],
            },
        ),
    ]
