# Generated by Django 5.2 on 2025-05-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='A list of strings: each one a key point'),
        ),
    ]
