# Generated by Django 5.2 on 2025-06-15 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exams_created', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='openendedquestion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_responses', to='courses.course'),
        ),
        migrations.AddField(
            model_name='openendedquestion',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_ended_question', to='profiles.personaldata'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='courses.course'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='courses.exam'),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='video',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.course'),
        ),
        migrations.AddField(
            model_name='video',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='openendedquestion',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_responses', to='courses.video'),
        ),
        migrations.AddField(
            model_name='wrongexamanswer',
            name='exam',
            field=models.ForeignKey(help_text="Which exam (e.g. 'midterm1' or 'final') this question came from.", on_delete=django.db.models.deletion.PROTECT, to='courses.exam'),
        ),
        migrations.AddField(
            model_name='wrongexamanswer',
            name='personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_exam_answers', to='profiles.personaldata'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexam',
            unique_together={('exam', 'student')},
        ),
    ]
