# Generated by Django 5.2 on 2025-05-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_video_key_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, default='courses/images/default-course-img.png', upload_to='courses/images/'),
        ),
    ]
