# Generated by Django 5.2 on 2025-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
