# Generated by Django 5.2 on 2025-06-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_studentexam_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexam',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
