# Generated by Django 5.2 on 2025-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(blank=True, default='courses/images/default_course_img_E4H4Mp2.jpg', upload_to='courses/images/'),
        ),
    ]
