# Generated by Django 5.2 on 2025-05-21 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='script',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
