# Generated by Django 5.2 on 2025-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_video_script_alter_presentation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='script',
            field=models.CharField(blank=True, null=True),
        ),
    ]
