# Generated by Django 5.2 on 2025-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_exam_studentexam'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_profiles', to='courses.course'),
        ),
    ]
